# Hydra config for CrossQ-GC algorithm

agent_name: CrossQGC # Used by main.py to select the agent class

# Parameters required by CrossQConfig dataclass
actor_lr: 3e-4
critic_lr: 3e-4
temp_lr: 3e-4
hidden_dims: [256, 256]
discount: 0.99
backup_entropy: True
init_temperature: 1.0
policy_log_std_min: -10.0
policy_log_std_max: 2.0
policy_final_fc_init_scale: 0.01
target_entropy_multiplier: 0.5
max_action: 1.0

# CrossQ specific parameters
use_batch_norm: True
n_critics: 2
policy_delay: 5
