# Hydra config for SAC-GC algorithm

agent_name: SACGC # Used by main.py to select the agent class

# Parameters required by SACGCConfig dataclass (assuming same as SACConfig for now)
actor_lr: 3e-4
critic_lr: 3e-4 # Note: SAC-GC might use a different LR for gamma critic, adjust if needed
temp_lr: 3e-4
hidden_dims: [256, 256]
discount: 0.99
tau: 0.005
target_update_period: 1
backup_entropy: True
init_temperature: 1.0
policy_log_std_min: -10.0
policy_log_std_max: 2.0
policy_final_fc_init_scale: 1.0
gamma_critic_lr: 3e-4
target_gamma_critic_update_period: 1

# Parameter used to calculate target_entropy in main.py
target_entropy_multiplier: 1.0 
max_action: 1.0
policy_delay: 1
