# Main configuration file


defaults:
  - env: mujoco/Ant-v4
  - _self_


# Training settings
training:
  max_steps: 1_000_000
  start_steps: 10_000
  eval_freq: 10_000
  batch_size: 256
  replay_buffer_capacity: 1_000_000
  eval_episodes: 10

# Algorithm settings
algorithm:
  actor_lr: 3e-4
  critic_lr: 3e-4
  temp_lr: 3e-4
  gamma_lr: 3e-4
  hidden_dims: [256, 256]
  discount: 0.99
  tau: 0.005
  target_update_period: 1
  backup_entropy: True
  init_temperature: 1.0
  target_entropy_multiplier: 1.0
  gamma_correction: True

# Logging settings
logging:
  use_wandb: True
  wandb_project: "sac_jax_hydra"
  wandb_entity: null

# Seed
seed: 42 