# Main configuration file
defaults:
  - environment: mujoco/Ant-v4 # Specify the default env file directly here
  - algorithm: sac
  - _self_

# Environment settings (define default values here)
# environment:
#   # Add any other default environment parameters that should apply
#   # if the selected env file (e.g., Ant-v4.yaml) doesn't define them.
#   # Example:
#   # render_mode: null

# Training settings
training:
  max_steps: 1_000_000
  start_steps: 10_000
  eval_freq: 10_000
  batch_size: 256
  replay_buffer_capacity: 1_000_000
  eval_episodes: 10
  update_frequency: 1

# Logging settings
logging:
  use_wandb: True
  wandb_project: "sac_jax_hydra_test"
  wandb_entity: null

# Seed
seed: 42 